const ratings = {
  None: {},
  'Catmaster-Partial': {
    'Seal Mender': 'S',
    'Fan of Blades': 'S',
    'Pure Agony': 'S',
    'Rotten Claws': 'S',
    'Hex Breaker': 'S',
    'Blessed Rebirth': 'S',
    'Chilling Presence': 'S',
    'Cold Conduction': 'S',
    'Unspeakable Gifts': 'S',
    Supercharge: 'S',
    'Deep Cuts': 'S',
    'Overwhelming Malice': 'S',
    'Purposeful Harbinger': 'S',
    Intensity: 'S',
    'Haunting Shout': 'S',
    'Wrapped in Flame': 'S',
    Fettle: 'S',
    'Sublime Sensation': 'S',
    'Master of Fear': 'S',
    'Self-Fulfilling Prophecy': 'S',
    'Holistic Health': 'S',
    'Will Shaper': 'S',
    'Spring Back': 'S',
    'Prismatic Carapace': 'S',
    'Prismatic Dance': 'S',
    Blessed: 'S',
    'Run Through': 'A',
    'Grim Oath': 'A',
    'Spiked Concoction': 'A',
    'Enduring Ward': 'A',
    'Precise Retaliation': 'A',
    'First Among Equals': 'A',
    "Mender's Wellspring": 'A',
    Bloodscent: 'A',
    Overlord: 'A',
    'Tempered Arrowheads': 'A',
    'Explosive Force': 'A',
    Devastator: 'A',
    'Pure Commander': 'A',
    'Vengeful Commander': 'A',
    'Stalwart Commander': 'A',
    "Doryani's Lesson": 'A',
    Snowstorm: 'A',
    'Wicked Pall': 'A',
    Renewal: 'A',
    'Skeletal Atrophy': 'A',
    'Primordial Bond': 'A',
    'Low Tolerance': 'A',
    'Eternal Suffering': 'A',
    'Wasting Affliction': 'A',
    'Flow of Life': 'A',
    'Vile Reinvigoration': 'A',
    'Circling Oblivion': 'A',
    Overshock: 'A',
    'Dark Discourse': 'A',
    'Wish for Death': 'A',
    Heraldry: 'A',
    'Invigorating Portents': 'A',
    Disciples: 'A',
    'Follow-Through': 'A',
    'Seeker Runes': 'A',
    'Brand Loyalty': 'A',
    'Set and Forget': 'A',
    'Expert Sabotage': 'A',
    'Careful Handling': 'A',
    'Peak Vigour': 'A',
    'Feast of Flesh': 'A',
    'Surging Vitality': 'A',
    'Peace Amidst Chaos': 'A',
    Adrenaline: 'A',
    'Wall of Muscle': 'A',
    Openness: 'A',
    Genius: 'A',
    'Energy From Naught': 'A',
    'Conservation of Energy': 'A',
    Militarism: 'A',
    'Natural Vigour': 'A',
    'No Witnesses': 'A',
    'Winter Prowler': 'A',
    Wizardry: 'A',
    Antivenom: 'A',
  },
}

const users = Object.keys(ratings)

export default ratings

export { users }
