const ratings = {
  None: {},
  Catmaster: {
    'Seal Mender': 'S',
    'Fan of Blades': 'S',
    'Pure Agony': 'S',
    'Rotten Claws': 'S',
    'Hex Breaker': 'S',
    'Blessed Rebirth': 'S',
    'Chilling Presence': 'S',
    'Cold Conduction': 'S',
    'Unspeakable Gifts': 'S',
    Supercharge: 'S',
    'Deep Cuts': 'S',
    'Overwhelming Malice': 'S',
    'Purposeful Harbinger': 'S',
    Intensity: 'S',
    'Haunting Shout': 'S',
    'Wrapped in Flame': 'S',
    Fettle: 'S',
    'Sublime Sensation': 'S',
    'Master of Fear': 'S',
    'Self-Fulfilling Prophecy': 'S',
    'Holistic Health': 'S',
    'Will Shaper': 'S',
    'Spring Back': 'S',
    'Prismatic Carapace': 'S',
    'Prismatic Dance': 'S',
    Blessed: 'S',
    'Run Through': 'A',
    'Grim Oath': 'A',
    'Spiked Concoction': 'A',
    'Enduring Ward': 'A',
    'Precise Retaliation': 'A',
    'First Among Equals': 'A',
    "Mender's Wellspring": 'A',
    Bloodscent: 'A',
    Overlord: 'A',
    'Tempered Arrowheads': 'A',
    'Explosive Force': 'A',
    Devastator: 'A',
    'Pure Commander': 'A',
    'Vengeful Commander': 'A',
    'Stalwart Commander': 'A',
    "Doryani's Lesson": 'A',
    Snowstorm: 'A',
    'Wicked Pall': 'A',
    Renewal: 'A',
    'Skeletal Atrophy': 'A',
    'Primordial Bond': 'A',
    'Low Tolerance': 'A',
    'Eternal Suffering': 'A',
    'Wasting Affliction': 'A',
    'Flow of Life': 'A',
    'Vile Reinvigoration': 'A',
    'Circling Oblivion': 'A',
    Overshock: 'A',
    'Dark Discourse': 'A',
    'Wish for Death': 'A',
    Heraldry: 'A',
    'Invigorating Portents': 'A',
    Disciples: 'A',
    'Follow-Through': 'A',
    'Seeker Runes': 'A',
    'Brand Loyalty': 'A',
    'Set and Forget': 'A',
    'Expert Sabotage': 'A',
    'Careful Handling': 'A',
    'Peak Vigour': 'A',
    'Feast of Flesh': 'A',
    'Surging Vitality': 'A',
    'Peace Amidst Chaos': 'A',
    Adrenaline: 'A',
    'Wall of Muscle': 'A',
    Openness: 'A',
    Genius: 'A',
    'Energy From Naught': 'A',
    'Conservation of Energy': 'A',
    Militarism: 'A',
    'Natural Vigour': 'A',
    'No Witnesses': 'A',
    'Winter Prowler': 'A',
    Wizardry: 'A',
    Antivenom: 'A',
    'Advance Guard': 'B',
    'Gladiatorial Combat': 'B',
    'Powerful Ward': 'B',
    "Gladiator's Fortitude": 'B',
    'Veteran Defender': 'B',
    'Replenishing Presence': 'B',
    'Precise Commander': 'B',
    Magnifier: 'B',
    'Vast Power': 'B',
    'Towering Threat': 'B',
    'Sleepless Sentries': 'B',
    'Enduring Focus': 'B',
    'Numbing Elixir': 'B',
    'Mob Mentality': 'B',
    'Cry Wolf': 'B',
    'Pressure Points': 'B',
    'Weight Advantage': 'B',
    'Force Multiplier': 'B',
    'Wind-up': 'B',
    'Arcing Shot': 'B',
    'Surefooted Striker': 'B',
    'Quick and Deadly': 'B',
    'Drive the Destruction': 'B',
    Thaumophage: 'B',
    'Master of Fire': 'B',
    Cremator: 'B',
    'Blanketed Snow': 'B',
    'Touch of Cruelty': 'B',
    'Unwaveringly Evil': 'B',
    'Dark Ideation': 'B',
    'Eldritch Inspiration': 'B',
    'Call to the Slaughter': 'B',
    'Hulking Corpses': 'B',
    'Vicious Bite': 'B',
    Blowback: 'B',
    'Cooked Alive': 'B',
    'Disorienting Wounds': 'B',
    'Deep Chill': 'B',
    Stormrider: 'B',
    'Forbidden Words': 'B',
    'Lasting Impression': 'B',
    'Dread March': 'B',
    'Life from Death': 'B',
    'Shrieking Bolts': 'B',
    Aerodynamics: 'B',
    Remarkable: 'B',
    'Grand Design': 'B',
    Expendability: 'B',
    'Arcane Pyrotechnics': 'B',
    'Liquid Inspiration': 'B',
    'Scintillating Idea': 'B',
    Improvisor: 'B',
    'Stubborn Student': 'B',
    'Savour the Moment': 'B',
    'Enduring Composure': 'B',
    'Flexible Sentry': 'B',
    'One with the Shield': 'B',
    Aerialist: 'B',
    'Elegant Form': 'B',
    "Molten One's Mark": 'B',
    'Prodigious Defence': 'C',
    'Strike Leader': 'C',
    'Iron Breaker': 'C',
    'Vicious Skewering': 'C',
    'Master of Command': 'C',
    'Savage Response': 'C',
    'Assert Dominance': 'C',
    'Ancestral Preservation': 'C',
    'Ancestral Guidance': 'C',
    'Vital Focus': 'C',
    'Unwavering Focus': 'C',
    'Rapid Infusion': 'C',
    'Precise Focus': 'C',
    'Stoic Focus': 'C',
    'Distilled Perfection': 'C',
    'Expansive Might': 'C',
    'Opportunistic Fusilade': 'C',
    "Storm's Hand": 'C',
    'Martial Mastery': 'C',
    'Combat Rhythm': 'C',
    'Fuel the Fight': 'C',
    'Conjured Wall': 'C',
    'Furious Assault': 'C',
    'Feed the Fury': 'C',
    'Essence Rush': 'C',
    Sadist: 'C',
    'Corrosive Elements': 'C',
    'Storm Drinker': 'C',
    'Cold to the Core': 'C',
    'Unholy Grace': 'C',
    'Raze and Pillage': 'C',
    'Burning Bright': 'C',
    'Vivid Hues': 'C',
    'Septic Spells': 'C',
    'Brush with Death': 'C',
    'Exposure Therapy': 'C',
    'Brewed for Potency': 'C',
    'Inspired Oppression': 'C',
    'Evil Eye': 'C',
    'Whispers of Death': 'C',
    Endbringer: 'C',
    'Empowered Envoy': 'C',
    'Dark Messenger': 'C',
    Streamlined: 'C',
    'Eye to Eye': 'C',
    Repeater: 'C',
    'Holy Conquest': 'C',
    'Guerilla Tactics': 'C',
    'Surprise Sabotage': 'C',
    Mindfulness: 'C',
    'Daring Ideas': 'C',
    'Heart of Iron': 'C',
    'Second Skin': 'C',
    'Dragon Hunter': 'C',
    Untouchable: 'C',
    'Rote Reinforcement': 'C',
    'Mage Hunter': 'C',
    'Pure Aptitude': 'C',
    'Pure Guile': 'C',
    'Pure Might': 'C',
    Sage: 'C',
    'Born of Chaos': 'C',
    'Rot-Resistant': 'C',
    'Student of Decay': 'C',
    'Lead By Example': 'C',
    'Titanic Swings': 'D',
    'Snaring Spirits': 'D',
    'Ancestral Inspiration': 'D',
    'Graceful Execution': 'D',
    'Insatiable Killer': 'D',
    'Martial Prowess': 'D',
    'Sap Psyche': 'D',
    'Arcane Adept': 'D',
    'Special Reserve': 'D',
    'Warning Call': 'D',
    'Wound Aggravation': 'D',
    Broadside: 'D',
    'Hit and Run': 'D',
    'Martial Momentum': 'D',
    'Prismatic Heart': 'D',
    'Cold-Blooded Killer': 'D',
    'Battle-Hardened': 'D',
    'Cult-Leader': 'D',
    Haemorrhage: 'D',
    'Astonishing Affliction': 'D',
    Thunderstruck: 'D',
    'Agent of Destruction': 'D',
    'Darting Movements': 'D',
    'Feasting Fiends': 'D',
    Bodyguards: 'D',
    'Clarity of Purpose': 'D',
    'Shifting Shadow': 'D',
    Readiness: 'D',
    'Vicious Guard': 'D',
    'Mystical Ward': 'D',
    Capacitor: 'D',
    Alchemist: 'D',
    Insulated: 'D',
    Antifreeze: 'D',
    Skullbreaker: 'E',
    'Eye of the Storm': 'E',
    'Quick Getaway': 'E',
    'Powerful Assault': 'E',
    'Ancestral Echo': 'E',
    'Ancestral Reach': 'E',
    Fasting: 'E',
    Provocateur: 'E',
    'Battlefield Dominator': 'E',
    'Rattling Bellow': 'E',
    'Master the Fundamentals': 'E',
    'Basics of Pain': 'E',
    'Smite the Weak': 'E',
    'Heavy Hitter': 'E',
    Calamitous: 'E',
    'Disorienting Display': 'E',
    'Widespread Destruction': 'E',
    'Smoking Remains': 'E',
    Paralysis: 'E',
    Rend: 'E',
    'Compound Injury': 'E',
    'Steady Torment': 'E',
    'Blast-Freeze': 'E',
    'Riot Queller': 'E',
    'Fire Attunement': 'E',
    'Non-Flammable': 'E',
    Hibernator: 'E',
    'Ancestral Might': 'F',
    'Disease Vector': 'F',
    'Brutal Infamy': 'F',
    'Fearsome Warrior': 'F',
    'Mage Bane': 'F',
    'Arcane Heroism': 'F',
    'Practiced Caster': 'F',
    'Burden Projection': 'F',
    'Fan the Flames': 'F',
    'Chip Away': 'F',
    Blacksmith: 'F',
  },
}

const users = Object.keys(ratings)

export default ratings

export { users }
